spring.application.name=taskplanner
spring.thymeleaf.cache=false

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

server.port=8080
